version: "3"
services:
  admin-app-container:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:admin-app
    command: >
      node server.js
    restart: always
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/admin-app-task-${PROJECT_NAME}-${ENV}
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: frontend
