# Docker Compose file
version: "3"
services:
  backend-container:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:backend
    restart: always
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_REGION=${AWS_REGION}
      - DOMAIN=${DOMAIN}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    volumes:
      - local_dynamic_storage:/home/storage
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2g
        

    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/backend-task-demo
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: backend

volumes:
  local_dynamic_storage:
