# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: AAQ
site_url: https://idinsight.github.io/aaq-core/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  icon:
    admonition:
      note: material/alert-circle
    annotation: material/help-circle

repo_url: https://github.com/IDinsight/aaq-core

nav:
  - Start here:
      - What is AAQ: index.md
      - Usage: usage.md
  - Deploying:
      - Quick setup: deployment/quick-setup.md
      - Architecture: deployment/architecture.md
  - Contributing:
      - Guidelines: develop/contributing.md
      - Setup: develop/setup.md
      - Testing: develop/testing.md
  - Admin App:
      - Managing content: content/admin-app.md
  - WhatsApp Connector:
      - Setup: whatsapp/setup.md
      - Testing: whatsapp/testing.md
  - Chat Managers:
      - Botpress v12 (OSS): chat_managers/botpress_v12.md
  - Offline LLMs:
      - Setup: self_hosted_llms/setup.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
