# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: AAQ
site_url: https://idinsight.github.io/aaq-core/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.sections
    - navigation.indexes
    - navigation.top
  icon:
    admonition:
      note: material/alert-circle
    annotation: material/help-circle

repo_url: https://github.com/IDinsight/aaq-core

nav:
  - 🏠 Welcome to AAQ:
      - What is AAQ?: index.md
      - Usage: usage.md
  - 📢 Latest Updates:
      - blog/index.md
  - ⚙️ Core Components:
      - components/index.md
      - Admin App:
          - components/admin-app/index.md
          - Access Levels: components/admin-app/access-level.md
          - Manage Content: components/admin-app/manage-content.md
          - Playground: components/admin-app/playground.md
      - Question-Answering Service:
          - components/qa-service/index.md
          - Semantic Search: components/qa-service/semantic-search.md
          - LLM Response: components/qa-service/llm-response.md
      - Triaging Service:
          - components/triaging/index.md
  - ➕ Other Components:
      - other-components/index.md
      - WhatsApp Connector:
          - other-components/whatsapp/index.md
          - Testing: other-components/whatsapp/testing.md
      - Chat Managers:
          - other-components/chat_managers/index.md
          - Botpress: other-components/chat_managers/botpress_v12.md
      - Offline LLMs:
          - other-components/self_hosted_llms/index.md
      - Align Score:
          - other-components/align-score/index.md
          - Deployment: other-components/align-score/deployment.md
          - Testing: other-components/align-score/testing.md
  - 🌀 Deploying:
      - Quick setup: deployment/quick-setup.md
      - Architecture: deployment/architecture.md
      - Configuring AAQ: deployment/config-options.md
  - 💝 Contributing:
      - Guidelines: develop/contributing.md
      - Setup: develop/setup.md
      - Testing: develop/testing.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search
  - blog:
      post_excerpt: required
