# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: AAQ

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    admonition:
      note: material/alert-circle
    annotation: material/help-circle

repo_url: https://github.com/IDinsight/aaq-core

repo_url: https://github.com/IDinsight/aaq-core

nav:
  - Getting Started: index.md
  - Content:
      - Managing content: content/admin-app.md
  - Developing:
      - Setup: develop/setup.md
      - Testing: develop/testing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
