site_name: "" # already part of the logo
site_description: "Ask A Question Documentation"
site_url: https://idinsight.github.io/aaq-core/
repo_url: https://github.com/IDinsight/aaq-core
copyright: "© 2024 IDinsight"
extra:
  generator: false
  social:
    - icon: material/shield-lock
      link: https://www.idinsight.org/about/privacy-policy/
      name: Privacy Policy

nav:
  - Home:
      - "": index.md
      - Usage: usage.md
      - Roadmap: roadmap.md

  - Latest Updates:
      - blog/index.md

  - Components:
      - components/index.md
      - User-facing components:
          - Admin App:
              - components/admin-app/index.md
              - Access Levels: components/admin-app/access-level.md
              - Manage Content: components/admin-app/manage-content.md
              - Playground: components/admin-app/playground.md
          - Question-Answering Service:
              - components/qa-service/index.md
              - Semantic Search: components/qa-service/semantic-search.md
              - LLM Response: components/qa-service/llm-response.md
      - Internal components:
          - LLM Proxy Server:
              - components/litellm-proxy/index.md
          - Align Score:
              - components/align-score/index.md
              - Deployment: components/align-score/deployment.md
              - Testing: components/align-score/testing.md

  - Integrations:
      - integrations/index.md
      - Chat Managers:
          - Typebot: integrations/chat_managers/typebot.md
          - Botpress: integrations/chat_managers/botpress_v12.md
      - WhatsApp Connector:
          - Setup: integrations/whatsapp/setup.md
          - Testing: integrations/whatsapp/testing.md

  - Deploy:
      - Quick setup with Docker Compose: deployment/quick-setup.md
      - Architecture: deployment/architecture.md
      - Configuring AAQ: deployment/config-options.md
      - AWS:
          - deployment/aws/index.md
          - Infrastructure: deployment/aws/infrastructure.md
          - CI/CD: deployment/aws/cicd.md

  - Contribute:
      - Guidelines: develop/contributing.md
      - Setup: develop/setup.md
      - Testing: develop/testing.md
      - Validation: develop/validation.md

# Themes and extensions
theme:
  name: material
  logo: images/logo-light.png
  favicon: images/favicon.png
  font:
    text: "Inter"
    code: "Roboto Mono"
  palette:
    - scheme: slate # Palette toggle for dark mode
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default # Palette toggle for light mode
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.sections
    - navigation.indexes
    - navigation.top
  icon:
    admonition:
      note: material/alert-circle
    annotation: material/help-circle

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page

plugins:
  - glightbox
  - search
  - blog:
      post_excerpt: required
