[tool.mypy]
#plugins = "sqlalchemy.ext.mypy.plugin"
#mypy_path = "$MYPY_CONFIG_FILE_DIR"
explicit_package_bases = true
disallow_untyped_defs = true

[tool.ruff]
select = ["E", "F", "B", "Q"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends"]
