[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ['litellm']
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "B", "Q", "I"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
markers = [
    "rails: marks tests that are testing rails are working correctly"
]
