[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "B", "Q"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
