version: "3.3"

services:
  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env
    depends_on:
      - botpress

  botpress:
    image: botpress/server:v12_31_3
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./build/botpress/data:/botpress/data

  postgres:
    image: postgres:11.2-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  pgdata:
