# Docker Compose file development
version: "3"
services:
  frontend-container:
    image: ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/aaq-demo-ecr-repository:frontend
    command: >
      npm start
    restart: always
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/admin-app-task-demo
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: frontend

