authors:
  Sid:
    name: Sid
    description: Data Science Director
    avatar: https://raw.githubusercontent.com/IDinsight/aaq-core/main/docs/blog/author-avatars/sid.png
  Carlos:
    name: Carlos
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/aaq-core/main/docs/blog/author-avatars/carlos.jpeg
  Amir:
    name: Amir
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/aaq-core/main/docs/blog/author-avatars/amir.jpeg
