steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - >
        "docker build "
        "-t ${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/litellm_proxy:latest  "
        "--build-arg OPENAI_API_KEY=$$OPENAI_API_KEY ."
    secretEnv: ["OPENAI_API_KEY"]
availableSecrets:
  secretManager:
    - version_name: "projects/$PROJECT_ID/secrets/${ _RESOURCE_PREFIX}-openai-api-key/versions/latest"
      env: OPENAI_API_KEY

images:
  - "${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${ _RESOURCE_PREFIX}/litellm_proxy:latest"
