steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - >
        docker build \
          -t ${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/caddy:latest \
          --build-arg DOMAIN=$$DOMAIN \
          .
    secretEnv: ["DOMAIN"]
availableSecrets:
  secretManager:
    - version_name: "projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-domain/versions/latest"
      env: DOMAIN

images:
  - "${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/caddy:latest"
