steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - >
        "docker build "
        "-t ${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/core_backend:latest "
        "-f Dockerfile.cloudbuild "
        "--build-arg JWT_SECRET=$$JWT_SECRET "
        "--build-arg NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID=$$NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID "
        "--build-arg DOMAIN=$$DOMAIN "
        "--build-arg LANGFUSE_SECRET_KEY=$$LANGFUSE_SECRET_KEY "
        "--build-arg LANGFUSE_PUBLIC_KEY=$$LANGFUSE_PUBLIC_KEY "
        "--build-arg POSTGRES_HOST=$$POSTGRES_HOST "
        "--build-arg POSTGRES_PASSWORD=$$POSTGRES_PASSWORD "
        "--build-arg ADMIN_USERNAME=$$ADMIN_USERNAME "
        "--build-arg ADMIN_PASSWORD=$$ADMIN_PASSWORD "
        "--build-arg ADMIN_API_KEY=$$ADMIN_API_KEY
        "."
    secretEnv:
      - "ADMIN_USERNAME"
      - "ADMIN_PASSWORD"
      - "ADMIN_API_KEY"
      - "JWT_SECRET"
      - "NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID"
      - "DOMAIN"
      - "LANGFUSE_SECRET_KEY"
      - "LANGFUSE_PUBLIC_KEY"
      - "POSTGRES_HOST"
      - "POSTGRES_PASSWORD"
availableSecrets:
  secretManager:
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-jwt-secret/versions/latest
      env: "JWT_SECRET"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-google-login-client-id/versions/latest
      env: "NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-domain/versions/latest
      env: "DOMAIN"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-langfuse-secret-key/versions/latest
      env: "LANGFUSE_SECRET_KEY"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-langfuse-public-key/versions/latest
      env: "LANGFUSE_PUBLIC_KEY"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-db-host/versions/latest
      env: "POSTGRES_HOST"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-db-password/versions/latest
      env: "POSTGRES_PASSWORD"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-admin-username/versions/latest
      env: "ADMIN_USERNAME"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-admin-password/versions/latest
      env: "ADMIN_PASSWORD"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-admin-api-key/versions/latest
      env: "ADMIN_API_KEY"

images:
  - "${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/core_backend:latest"
