steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - >
        docker build \
          --build-arg NEXT_PUBLIC_BACKEND_URL=https://$$DOMAIN/api \
          --build-arg NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID=$$NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID \
          -t ${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/admin_app:latest \
          .
    secretEnv: ["NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID", "DOMAIN"]
availableSecrets:
  secretManager:
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-google-login-client-id/versions/latest
      env: "NEXT_PUBLIC_GOOGLE_LOGIN_CLIENT_ID"
    - version_name: projects/$PROJECT_ID/secrets/${_RESOURCE_PREFIX}-domain/versions/latest
      env: "DOMAIN"

images:
  - "${_DOCKER_REGISTRY_DOMAIN}/$PROJECT_ID/${_RESOURCE_PREFIX}/admin_app:latest"
