version: "1"
services:
  botpress:
    image: botpress/server
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:secretpw@postgres:5435/botpress_db
      # - EXTERNAL_URL=http://localhost/
    depends_on:
      - postgres
    volumes:
      - ./build/botpress/data:/botpress/data
  postgres:
    image: postgres:11.2-alpine
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - botpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      /bin/sh -c "envsubst '$$\{DOMAIN\}' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
    env_file:
      - .env.nginx
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  pgdata:
