name: Alembic Migration Check

on:
  pull_request:
    branches:
      - tonyzhao6-main

jobs:
  alembic-check:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python libraries
        run: |
          python -m pip install -r core_backend/requirements.txt
      - name: Check Alembic heads
        run: |
          heads_count=$(alembic heads --resolve-dependencies | grep 'head' | wc -l)
          if [ "$heads_count" -gt 1 ]; then
            echo "Multiple Alembic heads detected. Please rebase or merge with the latest main branch."
            exit 1
          fi
