name: Alembic Migration Check

on:
  pull_request:
    branches:
      - tonyzhao6-main

jobs:
  alembic-check:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python libraries
        run: |
          python -m pip install -r core_backend/requirements.txt

      - name: Get Alembic head of tonyzhao6-main branch
        run: |
          git fetch origin tonyzhao6-main
          git worktree add /tmp/main-branch origin/tonyzhao6-main
          cd /tmp/main-branch
          alembic_head_main=$(alembic heads | awk '/head/ {print $NF}')
          echo "ALEMBIC_HEAD_MAIN=${alembic_head_main}" >> $GITHUB_ENV
          cd -

      - name: Get Alembic head of current branch
        run: |
          alembic_head_pr=$(alembic heads | awk '/head/ {print $NF}')
          echo "ALEMBIC_HEAD_PR=${alembic_head_pr}" >> $GITHUB_ENV

      - name: Compare Alembic heads
        run: |
          echo "Main branch Alembic head: ${{ env.ALEMBIC_HEAD_MAIN }}"
          echo "PR branch Alembic head: ${{ env.ALEMBIC_HEAD_PR }}"
          if [ "${{ env.ALEMBIC_HEAD_MAIN }}" != "${{ env.ALEMBIC_HEAD_PR }}" ]; then
            echo "Alembic head of the current branch (${{ env.ALEMBIC_HEAD_PR }}) is not the same as the Alembic head of tonyzhao6-main (${{ env.ALEMBIC_HEAD_MAIN }})."
            exit 1
          else
            echo "Alembic heads are the same."
          fi
