name: Deploying Caddy Container to Amazon ECS

on:
  push:
    branches:
      - demo
      - testing
    paths:
      - "deployment/aws/caddy/**"
      - ".github/workflows/deploy_caddy.yml"

jobs:
  DeployNginx:
    name: Deploying Nginx ${{github.ref_name}}
    runs-on: ubuntu-latest
    environment:
      name: ${{github.ref_name}}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{secrets.ROLE}}"
          role-session-name: deployrolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install the ECS CLI
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli

      - name: Create Task Definition
        if: steps.check_changes.outputs.changed == 'true'
        id: create-task-def
        run: |
          ecs-cli configure --cluster ${{ secrets.CLUSTER_NAME }} \
          --region ${{ secrets.AWS_REGION }} \
          --default-launch-type EC2 \
          --config-name ${{secrets.PROJECT_NAME}}-${{github.ref_name}}-caddy-config
          ecs-cli compose --project-name caddy-task --file deployment/aws/caddy/docker-compose.yml --task-role-arn ${{secrets.TASK_ROLE_ARN}} create
          echo "taskdef=caddy-task" >> $GITHUB_OUTPUT
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
          REPO: ${{ secrets.REPO }}
          PROJECT_NAME: ${{secrets.PROJECT_NAME}}
          ENV: ${{github.ref_name}}
          REGION: ${{secrets.REGION}}
      # We need this since deploy task definition action needs the task definition in json format

      - name: Task definition download
        id: download-task-def
        env:
          ecs_task_def_name: caddy-task
        run: |
          aws ecs describe-task-definition --task-definition "$ecs_task_def_name" --query taskDefinition > task-definition.json
          echo $(cat task-definition.json | jq 'del(
            .taskDefinitionArn,
            .requiresAttributes,
            .compatibilities,
            .revision,
            .status,
            .registeredAt,
            .registeredBy
          )') > task-definition.json
          echo "task-def=task-definition.json" >> $GITHUB_OUTPUT
      # This will update the service with the new task definition and wait for the deployment to finish
      # It waits for the service to become stable, which means that all tasks are running and there are no pending tasks
      # The drawback of this approach is that if none of the tasks starts, the deployment will be stuck in progress
      # This job will remain in progress until the deployment is finished
      - name: Deploy Amazon ECS task definition
        id: ecs-deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.download-task-def.outputs.task-def }}
          service: caddy-service
          cluster: ${{ secrets.CLUSTER_NAME }}
          wait-for-service-stability: true

      - name: Wait for Application to start
        id: wait-for-app
        run: sleep 1m
        shell: bash

      - name: Check if deployment was successful
        id: check-deployment
        run: |
          RUNNING_TASKS=$(aws ecs describe-services --cluster ${{ secrets.CLUSTER_NAME }} --services caddy-service --query services[0].deployments[0].runningCount | jq -r ".")

          if [ "$RUNNING_TASKS" -eq "0" ]; then
            echo "Deployment failed."
            exit 1
          fi
