name: Deploying Backend

on:
  push:
    branches:
      - AAQ-278-Create-Backend-Pipeline
    paths:
        - "core_backend/**"
        - ".github/workflows/**"

jobs:
    DeployFrontend:
        name: Deploying Backend demo
        runs-on: ubuntu-latest
        environment:
            name: demo
    
        permissions:
          id-token: write
          contents: read
        
        steps:
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
            - uses: actions/checkout@v4

            
            - name: Load .env file
              uses: xom9ikk/dotenv@v2
              with:
                path: ./.github/workflows
                mode: demo

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{env.ROLE}}"
                role-session-name: deployrolesession
                aws-region: ${{ env.AWS_REGION }}
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com


            - name: Build and push
              id: build-image
              uses: docker/build-push-action@v5
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: aaq-demo-ecr-repository
                IMAGE_TAG: Backend
              with:
                context: core_backend
                platforms: linux/arm64
                file: core_backend/Dockerfile.demo
                cache-from: type=gha
                cache-to: type=gha
                push: true
                tags: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
                build-args: |
                  BOOTSTRAP_FILE=${{env.BOOTSTRAP_FILE}}

                

            - name: Install the ECS CLI
              run: |
                sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
                sudo chmod +x /usr/local/bin/ecs-cli
            - name: Create Task Definition
              id: create-task-def
              run: |
                ecs-cli configure --cluster ${{ env.CLUSTER_NAME }} \
                --region ${{ env.AWS_REGION }} \
                --default-launch-type EC2 \
                --config-name aaq-demo-backend-config
                ecs-cli compose --project-name backend-task --file core_backend/deployment/docker-compose.yml create
                echo "taskdef=backend-task" >> $GITHUB_OUTPUT
              env:
                AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
                AWS_REGION: ${{ env.AWS_REGION }}
                QDRANT_HOST: ${{ env.QDRANT_HOST }}
                NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
                DOMAIN: ${{ env.DOMAIN }}
            # We need this since deploy task definition action needs the task definition in json format
            - name: Task definition download
              id: download-task-def
              env:
                ecs_task_def_name: backend-task
              run: |
                aws ecs describe-task-definition --task-definition "$ecs_task_def_name" --query taskDefinition > task-definition.json
            
            - name: Fill in the new image ID in the Amazon ECS task definition
              id: task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                task-definition: task-definition.json
                container-name: backend-container
                image: ${{ fromJson(steps.build-image.outputs.metadata)['image.name'] }}
            
            - name: Deploy Amazon ECS task definition
              id: ecs-deploy
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: backend-service
                cluster: ${{ env.CLUSTER_NAME }} 
                wait-for-service-stability: true
            - name: Check if deployment was successful
              id: check-deployment
              run: |
                  CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services backend-service --query services[0].deployments[0].taskDefinition | jq -r ".")
                  NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
                  echo "Current task arn: $CURRENT_TASK_DEF_ARN"
                  echo "New task arn: $NEW_TASK_DEF_ARN"
                  if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
                    echo "Deployment failed."
                    exit 1
                  fi
                
                