name: Deploy LiteLLM Proxy to GCP

on:
  push:
    branches:
      - main
      - testing
      - deploy-on-gcp-ga
    paths:
      - "deployment/docker-compose/litellm_proxy/**"
      - "deployment/gcp/cloudbuild_litellm_proxy.yaml"
      - ".github/workflows/deploy_gcp_litellm_proxy.yaml"
  workflow_dispatch:

jobs:
  DeployLiteLLMProxyToGCP:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    environment: gcp-testing

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker asia-south2-docker.pkg.dev

      - name: Build and push LiteLLM Proxy image
        working-directory: deployment/docker-compose/litellm_proxy
        env:
          RESOURCE_PREFIX: ${{ secrets.PROJECT_NAME }}-${{ (github.ref_name == 'deploy-on-gcp-ga' && 'testing') || github.ref_name }}
          # TODO: change deploy-on-gcp-ga to main
        run: |
          gcloud builds submit --config=../../gcp/cloudbuild_litellm_proxy.yaml \
            --substitutions \
              _RESOURCE_PREFIX=${{ env.RESOURCE_PREFIX }},_DOCKER_REGISTRY_DOMAIN=${{ secrets.DOCKER_REGISTRY_DOMAIN }}

      - name: Get docker repository prefix
        id: "docker_repository"
        run: |
          echo "docker_repository=${{ secrets.DOCKER_REGISTRY_DOMAIN }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PROJECT_NAME }}-${{ (github.ref_name == 'deploy-on-gcp-ga' && 'testing') || github.ref_name }}" >> $GITHUB_OUTPUT
        # TODO: change deploy-on-gcp-ga to main

      - name: Deploy LiteLLM Proxy container
        id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "${{ secrets.DEPLOYMENT_INSTANCE_NAME }}"
          zone: "${{ secrets.DEPLOYMENT_ZONE }}"
          ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
          command: |
            docker-credential-gcr configure-docker \
              --registries ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
            docker pull \
              ${{ steps.docker_repository.outputs.docker_repository }}/litellm_proxy:latest
            docker stop litellm_proxy
            docker rm litellm_proxy
            docker run -d \
              --log-driver=gcplogs \
              --restart always \
              --network aaq-network \
              --name litellm_proxy \
              ${{ steps.docker_repository.outputs.docker_repository }}/litellm_proxy:latest
            docker system prune --volumes -f
