name: Deploy main to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script_stop: true
            script: |
                cd /home/${{ secrets.SSH_USERNAME }}/aaq-core/deployment &&
                docker-compose -f docker-compose.yml -p aaq-stack down &&
                git fetch --all &&
                git switch main &&
                git reset --hard origin/main &&
                git pull origin main &&
                docker-compose -f docker-compose.yml -p aaq-stack up -d --build
