name: Deploy Caddy to GCP

on:
  push:
    branches:
      - main
      - testing
    paths:
      - "deployment/docker-compose/caddy/**"
      - "deployment/gcp/cloudbuild_caddy.yaml"
      - ".github/workflows/deploy_gcp_caddy.yaml"
  workflow_dispatch:

jobs:
  DeployCaddyToGCP:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    environment: gcp-testing

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker asia-south2-docker.pkg.dev

      - name: Build and push caddy image
        working-directory: deployment/docker-compose/caddy
        env:
          RESOURCE_PREFIX: ${{ secrets.PROJECT_NAME }}-${{ (github.ref_name == 'main' && 'testing') || github.ref_name }}
          # TODO: change deploy-on-gcp-ga to main
        run: |
          gcloud builds submit --config=../../gcp/cloudbuild_caddy.yaml \
            --substitutions \
              _RESOURCE_PREFIX=${{ env.RESOURCE_PREFIX }},_DOCKER_REGISTRY_DOMAIN=${{ secrets.DOCKER_REGISTRY_DOMAIN }}

      - name: Get docker repository prefix
        id: "docker_repository"
        run: |
          echo "docker_repository=${{ secrets.DOCKER_REGISTRY_DOMAIN }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PROJECT_NAME }}-${{ (github.ref_name == 'main' && 'testing') || github.ref_name }}" >> $GITHUB_OUTPUT
        # TODO: change deploy-on-gcp-ga to main

      - name: Deploy Caddy container
        id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "${{ secrets.DEPLOYMENT_INSTANCE_NAME }}"
          zone: "${{ secrets.DEPLOYMENT_ZONE }}"
          ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
          command: |
            docker-credential-gcr configure-docker \
                --registries ${{ secrets.DOCKER_REGISTRY_DOMAIN }}
            docker pull ${{ steps.docker_repository.outputs.docker_repository }}/caddy:latest
            docker stop caddy
            docker rm caady
            docker run -d \
                -v caddy_data:/data \
                -v caddy_config:/config \
                -p 80:80 \
                -p 443:443 \
                -p 443:443/udp \
                --log-driver=gcplogs \
                --restart always \
                --network aaq-network \
                --name caddy \
                ${{ steps.docker_repository.outputs.docker_repository }}/caddy:latest
            docker system prune --volumes -f
