name: Deploy any branch to dev
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Branch do deploy on test server"
        type: string
  push:
    branches:
      - AAQ-125-autodeploy-dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github_actions_dev
          role-session-name: github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker tag and push backend image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA_SHORT: $(git rev-parse --short "$GITHUB_SHA")
        run: |
          docker build -f ./core_backend/Dockerfile -t $ECR_REGISTRY/aaq-core-backend:latest ./core_backend
          docker push $ECR_REGISTRY/aaq-core-backend:latest

          docker tag $ECR_REGISTRY/aaq-core-backend:latest $ECR_REGISTRY/aaq-core-backend:$SHA_SHORT
          docker push $ECR_REGISTRY/aaq-core-backend:$SHA_SHORT

      - name: Docker tag and push admin app image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA_SHORT: $(git rev-parse --short "$GITHUB_SHA")
        run: |
          docker build -f ./admin_app/Dockerfile -t $ECR_REGISTRY/aaq-admin-app:latest ./admin_app
          docker push $ECR_REGISTRY/aaq-admin-app:latest

          docker tag $ECR_REGISTRY/aaq-admin-app:latest $ECR_REGISTRY/aaq-admin-app:$SHA_SHORT
          docker push $ECR_REGISTRY/aaq-admin-app:$SHA_SHORT
