name: Retrieval validation

on:
  push:
    branches:
      - main
      - AAQ-81-retrieval-val

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  validate:
    runs-on: ubuntu-20.04
    container: node:20.7-bullseye
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
    environment: validation-mc
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_dev
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          python -m pip install -r core_backend/requirements.txt
          python -m pip install -r core_backend/validation/requirements.txt

      - name: Run validation script
        run: |
          python core_backend/validation/validate.py \
            --validation_data_path \
              ${{ secrets.VALIDATION_DATA_S3_PATH }} \
            --content_data_path \
              ${{ secrets.CONTENT_DATA_S3_PATH }} \
            --validation_data_question_col \
              ${{ vars.VALIDATION_DATA_QUESTION_COL }} \
            --validation_data_label_col \
              ${{ vars.VALIDATION_DATA_LABEL_COL }} \
            --content_data_label_col \
              ${{ vars.CONTENT_DATA_LABEL_COL }} \
            --content_data_text_col \
              ${{ vars.CONTENT_DATA_TEXT_COL }}
