name: Retrieval validation

on:
  push:
    branches: [main]
    paths:
      - "core_backend/**"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  validate:
    runs-on: ubuntu-20.04
    container: node:20.7-bullseye
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
    environment: validation-mc
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y lsb-release && apt-get clean all

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_dev
          role-session-name: github-actions
          role-duration-seconds: 7200
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CloudWatch log stream
        run: |
          timestamp=$(date +%Y-%m-%d-%H-%M-%S)
          log_stream="${timestamp}-${{ github.run_id }}-${{ github.sha }}"
          aws logs create-log-stream --log-group-name "${{ vars.LOG_GROUP }}" --log-stream-name "$log_stream"
          echo "LOG_STREAM=$log_stream" >> $GITHUB_ENV

      - name: AWS CloudWatch log stream link
        run: |
          log_url=$(python core_backend/validation/log_config.py)
          echo "Find the full log of this workflow run at $log_url"
          echo "LOG_URL=$log_url" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install -r core_backend/requirements.txt
          python -m pip install -r core_backend/validation/requirements.txt

      - name: Run validation script
        env:
          QDRANT_COLLECTION_NAME: validation_collection
          QDRANT_N_TOP_SIMILAR: 10
          QDRANT_PORT: 6333
          PROMETHEUS_MULTIPROC_DIR: /tmp
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_HOST: qdrant
          REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          python -m pytest core_backend/validation/validate_retrieval.py \
            --validation_data_path \
              ${{ secrets.VALIDATION_DATA_S3_PATH }} \
            --content_data_path \
              ${{ secrets.CONTENT_DATA_S3_PATH }} \
            --validation_data_question_col \
              ${{ vars.VALIDATION_DATA_QUESTION_COL }} \
            --validation_data_label_col \
              ${{ vars.VALIDATION_DATA_LABEL_COL }} \
            --content_data_label_col \
              ${{ vars.CONTENT_DATA_LABEL_COL }} \
            --content_data_text_col \
              ${{ vars.CONTENT_DATA_TEXT_COL }} \
            --notification_topic \
              arn:aws:sns:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:aaq-validation-topic \
            -n auto -s
