name: Unit Tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-20.04
    container: node:20.7-bullseye
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres-test-pw
          POSTGRES_USER: postgres-test-user
          POSTRGES_DB: postgres-test-db
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          -e POSTGRES_USER
          -e POSTGRES_DB
        ports:
          - 5433:5432

    steps:
      - name: install dependencies
        run: apt-get update && apt-get install -y lsb-release && apt-get clean all
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Python libraries
        run: |
          python -m pip install -r core_backend/requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Run Unit Tests
        run: |
          cd core_backend
          python -m pytest
